### ISSUE TITLE
Мне кажется тг бот намного лучше подойдет для твоего функционала

### ISSUE THREAD

**Issue by polinavenberg** [artlvruran/WeatherWeb#2]

**Comment by artlvruran** [comment]
Какие конкретно преимущества будут у телеграмм-бота перед сайтом? Как мне кажется, в плане функционала существенных различий нету. В веб-приложении пользовательский интерфейс будет менее топорным и его можно самому настроить через css. Да и я уже очень много сделал именно по веб-приложению
